version: '3.8'

services:

  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: java-challenge
      POSTGRES_PASSWORD: java-challenge
      POSTGRES_DB: java-challenge
    ports:
      - "5432:5432"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d



